import Head from 'next/head'
import Header from '../components/organism/Header'
import Carousel from '../components/organism/Carousel'
import styles from '../styles/Home.module.css'
import Welcome from '../components/organism/Welcome'
import Review from '../components/organism/Review'
import Footer from '../components/organism/Footer'
import Image from 'next/image'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/vbe1upt.css"></link>
      </Head>
      <Header className={styles.header}/>

      <main className={styles.main}>
        <Carousel className={styles.Carousel}/>
        <Welcome/>
        <Review />
      </main>
      <Footer />
    </div>
  )
}
